export const allWines = [
  {
    flag: "/flag-italy.png",
    image: "/wine-red.png",
    percentile: "12",
    originTown: "lombardy",
    year: "2021",
    color: "red",
    winemaker: "chevalier wines",
    title: "lorem ipsum",
    price: 12.99,
  },
  {
    flag: "/flag-france.png",
    image: "/wine-fancy.png",
    percentile: "13",
    originTown: "bordeaux",
    year: "2015",
    color: "red",
    winemaker: "pinot noir",
    title: "domaine serene",
    price: 17.99,
  },
  {
    flag: "/flag-georgia.png",
    image: "/wine-white.png",
    percentile: "11",
    originTown: "tbilisi",
    year: "2017",
    color: "white",
    winemaker: "cullen",
    title: "margaret river",
    price: 24.99,
  },
];
