"use client";
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components";
import { usePathname } from "next/navigation"; // Use Next.js' usePathname hook

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname(); // Get the current route

  const getBackgroundColor = () => {
    if (pathname === "/wine") {
      return "bg-secondary";
    } else {
      return "bg-background";
    }
  };

  return (
    <html lang="en">
      <body className={`${getBackgroundColor()} min-h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
